trim_ctors: true
trim_dtors: true
symbol_aligns:
    0x8064d500 : 0x20
    0x81295C80 : 0x20 # .bss m_handbill.o
    0x8125a7c0 : 0x20 # construct_skip
    0x81361820 : 0x20 # S_back_title_timer
    0x806D4D40: 32 # align fFTR_myhome_off_pal_table to 32 bytes
    0x8064F860: 32 # data right after m_camera2 TU
    0x80C78B20: 32 # mFM_grd_s_cliff_tex
    0x80F8C460: 32 # mFM_grd_s_rail_tex
    0x80657200: 32 # .data msg.o
    0x81297E80: 32 # .bss msg.o
    0x81296140: 32 # .bss m_island.o
    0x80904700: 32 # rom_myhome1_floor_v
    0x80751140: 32 # dataobject.obj/.data/obj_zassou_tex
