trim_ctors: true
trim_dtors: true
symbol_aligns:
    0x8064d500 : 0x20
    0x81295C80 : 0x20 # .bss m_handbill.o
    0x8125a7c0 : 0x20 # construct_skip
    0x81361820 : 0x20 # S_back_title_timer
    0x806D4D40: 32 # align fFTR_myhome_off_pal_table to 32 bytes
    0x8064F860: 32 # data right after m_camera2 TU
    0x80C78B20: 32 # mFM_grd_s_cliff_tex
    0x80F8C460: 32 # mFM_grd_s_rail_tex
    0x80657200: 32 # .data msg.o
    0x81297E80: 32 # .bss msg.o
    0x81296140: 32 # .bss m_island.o
    0x80904700: 32 # rom_myhome1_floor_v
    0x80751140: 32 # dataobject.obj/.data/obj_zassou_tex
    0x80DD61A0: 32 # dataobject/obj/.data/cKF_ckcb_r_int_hnw001_tbl (TU is aligned to 32 because of 32-byte aligned entries)
    0x80F1CCA0: 32 # dataobject/obj/.data/rom_museum5_wall_pal
    0x80F85720: 32 # dataobject/obj/.data/grd_player_select_evw_anime_1 (TU is aligned to 32)
    0x80FACE20: 32 # dataobject/obj/.data/rom_shop4_1_floor_tex_pal
    0x8074B840: 32 # dataobject/obj/.data/mFM_obj_a_01_flower_pal
    0x808DF220: 32 # obj_otiba01_pal
    0x809C8FA0: 32 # ef_hanabira01_0
    0x80C0CBA0: 32 # crw_anrium1_pal